project_name: tailscale-systray
builds:
  - env:
      - CGO_ENABLED=1 # required for systray
    no_unique_dist_dir: true
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386