project_name: tailscale-systray
builds:
  - no_unique_dist_dir: true
    goos:
      - windows
      - linux
      # - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
    overrides:
      - goos: darwin
        goarch: amd64
        goamd64: v1
        goarm: ""
        gomips: ""
        env:
          - CGO_ENABLED=1
