name: Build the program

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  clean_old:
    runs-on: ubuntu-latest
    name: Clean old releases
    steps:
      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: clean_old
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-latest
            goos: linux
            ext: ""
            flags: ""
          - runs-on: windows-latest
            goos: windows
            ext: ".exe"
            flags: "-ldflags -H=windowsgui"
          - runs-on: macos-latest
            goos: darwin
            ext: ""
            flags: ""
        arch:
          - goarch: amd64
            skip-if-os: ""
          - goarch: arm64
            skip-if-os: darwin
          - goarch: 386
            skip-if-os: darwin
    runs-on: ${{ matrix.os.runs-on }}
    name: Build ${{ matrix.os.goos }}/${{ matrix.arch.goarch }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build
        if: ${{ matrix.os.goos != matrix.arch.skip-if-os }}
        run: |
          go generate .
          env GOOS=${{ matrix.os.goos }} GOARCH=${{ matrix.arch.goarch }} go build ${{ matrix.os.flags }} -o tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}${{ matrix.os.ext }}
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}${{ matrix.os.ext }}