name: Build the program

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-latest
            goos: linux
          - runs-on: windows-latest
            goos: windows
          - runs-on: macos-latest
            goos: darwin
        arch:
          - goarch: amd64
            skip-if-os: ""
          - goarch: arm64
            skip-if-os: darwin
          - goarch: 386
            skip-if-os: darwin
    runs-on: ${{ matrix.os.runs-on }}
    name: Build ${{ matrix.os.goos }}/${{ matrix.arch.goarch }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build
        if: ${{ matrix.os.goos != matrix.arch.skip-if-os }}
        run: env GOOS=${{ matrix.os.goos }} GOARCH=${{ matrix.arch.goarch }} go build -o tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: |
            tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}