name: Build the program

on:
  push:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-latest
            goos: linux
          - runs-on: windows-latest
            goos: windows
          - runs-on: macos-latest
            goos: darwin
        arch:
          - goarch: amd64
            skip-if-os: ""
          - goarch: arm64
            skip-if-os: darwin
          - goarch: 386
            skip-if-os: darwin
    runs-on: ${{ matrix.os.runs-on }}
    name: Build ${{ matrix.os.goos }}/${{ matrix.arch.goarch }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'
      - name: Build
        if: ${{ matrix.os.goos != matrix.arch.skip-if-os }}
        run: env GOOS=${{ matrix.os.goos }} GOARCH=${{ matrix.arch.goarch }} go build -o tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}
      - name: Upload artifact
        if: ${{ matrix.os.goos != matrix.arch.skip-if-os }}
        uses: actions/upload-artifact@v2
        with:
          name: tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}
          path: tailscale-systray-${{ matrix.os.goos }}-${{ matrix.arch.goarch }}

  collect:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download all matrix artifacts
        uses: actions/download-artifact@v2
        with:
          name: tailscale-systray-*
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: true
          files: |
            tailscale-systray-*
          title: "Latest development build"